/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_Box */

#ifndef _Included_com_example_Box
#define _Included_com_example_Box
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_Box
 * Method:    ctorCPP
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_Box_ctorCPP
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_Box
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_Box_get
  (JNIEnv *, jobject);

/*
 * Class:     com_example_Box
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_Box_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
