/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_Hello */

#ifndef _Included_com_example_Hello
#define _Included_com_example_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_Hello
 * Method:    addInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_Hello_addInt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_Hello
 * Method:    addStr
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_Hello_addStr
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
