/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_Hello */

#ifndef _Included_com_example_Hello
#define _Included_com_example_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_Hello
 * Method:    modifyArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_example_Hello_modifyArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
